# RespoBot constants

PLEB_LINE = 2500
RESPO_WEEKS_TO_COUNT = 6
RESPO_SERIES_NAME = 'Respo Racing Whatever the Fuck You Want Series'
IRACING_FIRST_YEAR = 2008
IRACING_FIRST_QUARTER = 1
CPI_CORNERS_INCLUDED = 2000
CLOSE_FINISH_INTERVAL_MS = 100
NOTABLE_POSITION_CHANGE = 5
NOTABLE_FINISH_POS_RELATIVE_TO_CAR_NUM = 10
NOTABLE_IRATING_CHANGE = 75
REFERENCE_SERIES = 139
FAST_LOOP_INTERVAL = 75
SLOW_LOOP_INTERVAL = 600
IRACING_CATEGORIES = ['road', 'oval', 'dirt_road', 'dirt_oval']
PRONOUN_TYPES = ['male', 'female', 'neutral']
RESPO_LOGO_FILENAME = 'respo_logo.png'
BASE_AVATAR_FILENAME = 'base_avatar.png'
IMAGE_FONT_FILENAME = 'lucon.ttf'
