# RespoBot constants

PLEB_LINE = 2500
RESPO_WEEKS_TO_COUNT = 6
RESPO_SERIES_NAME = 'Respo Racing Whatever the Fuck You Want Series'
IRACING_FIRST_YEAR = 2008
IRACING_FIRST_QUARTER = 1
RACE_SCAN_INTERVAL = 120
